[package]
name = "bacon_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-debouncer-full = "0.2"
paste = "1"
